codecov:
  branch: main
  ignore:
    - 'dev_suites/onc_program/**/*'
    - 'dev_suites/smart_scheduling_links/**/*'
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
